myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"

urlpatterns = [
    path('trail/',views.trail,name="trail"),
    path('about/',views.about,name="about"),
    path('download/',views.download,name="download"),
    path('document/',views.document,name="document"),
    path('get_demo/',views.get_demo,name="get_demo"),

]

p5/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp 
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',views.base,name="base"),
    path('',views.home,name="home"),
    path('myapp/',include("myapp.urls")),
]

webpage/webpage/urls.py
from django.contrib import admin
from django.urls import path
from webpage import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

def trail(request):
    return HttpResponse("<h1>project done</h1>")
# Create your views here.
def base(request):
    return render(request,"base.html")

def home(request):
    return render(request,"home.html")

def about(request):
    return render(request,"about.html")

def download(request):
    return render(request,"download.html")

def document(request):
    return render(request,"document.html")

def get_demo(request):
    return render(request,"get_demo.html")

webpage/webpage/views.py
from django.http import HttpResponse
from django.shortcuts import render



def home(request):
    return render(request,'home.html',{"name":"Aditya"})

templates/about.html
{% extends "base.html" %}

{% block title %}
    <title>About Page</title>
    {% endblock  %}

    {% block h1 %}
    <div class="container">
        <div class="jumbotron">
            <p style="font-size:25px;color:green"><b>Python is a programming language that lets you<br> work more quickly and integrate your systems<br> more effectively.</b></p>

               <p> You can learn to use Python and see almost immediate<br> gains in productivity and lower maintenance costs.</p>
               <p style="color:green;"> Learn more about Python.</p>
        </div>
    </div>
    
    {% endblock h1 %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Document</title>
    {% endblock  %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</head>
<body style="background-color:#1c87c9;"> 
    
      {% include "partial/_topbar.html" %}
      {% include "partial/_navbar.html" %}
      <!---<img src="{% static 'image/python2.png' %}" alt="no image found" height="80" width="130">-->
      
    {% block h1 %}
    <div class="container">
        <div class="jumbotron">
            <h1>Python is amazing</h1>
            <img src="{% static 'image/py.png' %}" alt="no image found" height="80" width="130">
            <img src="{% static 'image/g1.png' %}" alt="no image found" height="80" width="130">
            <img src="{% static 'image/g2.png' %}" alt="no image found" height="80" width="130">
            <img src="{% static 'image/g3.png' %}" alt="no image found" height="80" width="130">
            <img src="{% static 'image/g4.png' %}" alt="no image found" height="80" width="130">
        </div>
    </div>
    {% endblock h1 %}
    {% include "partial/_python.html" %}
    
</body>
</html>

templates/document.html
{% extends "base.html" %}

{% block title %}
    <title>Download Page</title>
    {% endblock  %}

    {% block h1 %}
    <div class="container">
        <div class="jumbotron">
            <p style="font-size:25px;color:green;">Browse the docs online or download a copy of your own.</p>
            <button>Python 3.8.5</button>
        </div>
    </div>
    {% endblock h1 %}

templates/download.html
{% extends "base.html" %}

{% block title %}
    <title>Download Page</title>
    {% endblock  %}

    {% block h1 %}
    <div class="container">
        <div class="jumbotron">
            <p style="font-size:25px;color:green;">Download for windows</p>
            <button>Python 3.8.5</button>
        </div>
    </div>
    {% endblock h1 %}

templates/get_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>get file </title>
</head>
<body>
    <form method="GET">
        <label for="name">name</label>
        <input type="text"name="name"id="name">
        <input type="button" value="submit">
    </form>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}
    <title>Home Page</title>
    {% endblock  %}

    {% block h1 %}
    <div class="container">
        <div class="jumbotron">
              
            <h1>django is framwork</h1>
        </div>
    </div>
    {% endblock h1 %}

templates/partial/_navbar.html
<div class="container">
    <ul class="nav">
        <li class="nav-item">
          <a style="color: black;" class="nav-link active" href="{% url 'home'%}">Home</a>
        </li>
        <li class="nav-item">
          <a style="color: black;" class="nav-link" href="{% url 'myapp:about'%}">About</a>
        </li>
        <li class="nav-item">
          <a style="color: black;" class="nav-link" href="{% url 'myapp:download'%}">Download</a>
        </li>
        <li class="nav-item">
          <a style="color: black;" class="nav-link" href="{% url 'myapp:document'%}">Document</a>
        </li>
      </ul>
  </div>

templates/partial/_python.html
<div class="alert alert-primary" role="alert">
    <center>python is love</center>
  </div>

templates/partial/_topbar.html
<div class="alert alert-secondary" role="alert">
    <center><h1>Python</h1></center>
  </div>

templates/profile.html
{% extends "base.html" %}

{% block title %}
    <title>Profile Page</title>
    {% endblock  %}

    {% block h1 %}
    <div class="container">
        <div class="jumbotron">
            <center>welcome to {{name}} profile page</center>
        </div>
    </div>
    {% endblock h1 %}